name: Create diagram
on:
  push:
    branches:
      - main

jobs:
  get_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: "Writing/Figures/diagram.svg"
          excluded_paths: "node_modules,dist"
